# Generated by Django 2.1.4 on 2020-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor', '0003_auto_20191104_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
